### PR TITLE
adding navbar brand logo and hyperlink

### LINKED ISSUE #375: Place SamveraTM Logo at prominent place
### Descriptive summary of request
from https://samvera.slack.com/messages/C0F9JQJDQ/

Richard Green  
@channel I'm not entirely sure who amongst us now maintains samvera.github.io for documentation - but this is aimed at that team.  We are applying to trademark the Samvera logo in the US, Canada & Europe and we're advised that it would help the process if the tree were more prominently positioned on these documentation pages.  At the moment it's bottom right and not necessarily obvious unless you scroll right down.  If it could be placed top left above the facets (even if it needed to be a little smaller to accommodate this) that could be very beneficial.  Can anyone oblige, please?

### Existing 
At the moment it's bottom right and not necessarily obvious unless you scroll right down. 

### Expected
* [ ] If it could be placed top left above the facets (even if it needed to be a little smaller to accommodate this) that could be very beneficial. 

### Related work
#376

### PR DESCRIPTION
**Pull request by jmfrenzel**
Implements company logo and hyperlink in page top navbar. 

Size of the logo is subject to be adapted, cf. planned layout re factoring. 

Closes #375

### CODE REVIEW

**Comment by afred** [comment]
image

**Comment by jmfrenzel** [comment]
get the navbar top aligned with page H1 title like  in the original theme and prior this change  https://github.com/samvera/samvera.github.io/pull/376#issuecomment-442135268

**Comment by afred** [comment]
@laritakr @bess @jmfrenzel well shucks.... a lot of those quick modifications I made totally screwed up the responsiveness of the top menu to a point where I wouldn't want to push it.

I will go back and put the modifications in better places within the CSS (rather than just overwriting rules at the bottom of `customstyles.css`) and see if that un-breaks it.

**Comment by laritakr** [comment]
Closed, as work was done via PR #377 instead.

**Pull request closed without merging**
