### PR TITLE
how to configure notification polling intervals

### PR DESCRIPTION
**Pull request by jenlindner**

### CODE REVIEW

**Comment by jcoyne** [comment]
Is this only for Hyrax 1.0?  Should that be noted?

**Comment by jenlindner** [comment]
@jcoyne yeah, I removed the H1 that noted it without realizing that was the only place that did it. Thanks.

**Comment by bess** [comment]
@jenlindner Is this PR still active?

**Comment by laritakr** [comment]
Relates to https://github.com/samvera/hyrax/issues/2151

**Comment by afred** [comment]
Going to add version front matter, and then approve. Stand by.

**Comment by afred** [comment]
backfilled a ticket for this: #253

**Comment by afred** [comment]
Looks like this...

image

**Pull request merged**
